// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCr5CDtPBDdCt_NCMhK_MOZrHOJSHXwZA',
    appId: '1:284300220036:web:6dd8a80c1246a2f4d4d4d1',
    messagingSenderId: '284300220036',
    projectId: 'chat-clone-cbea7',
    authDomain: 'chat-clone-cbea7.firebaseapp.com',
    storageBucket: 'chat-clone-cbea7.appspot.com',
    measurementId: 'G-LYD5ZFF9VW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU_QId3QvcPipX2aXxQB57CficDemMBUQ',
    appId: '1:284300220036:android:26fc9b71ed085e52d4d4d1',
    messagingSenderId: '284300220036',
    projectId: 'chat-clone-cbea7',
    storageBucket: 'chat-clone-cbea7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC10VfUnR0lhhrFzx10Hs1qR8Nu_1FgRQo',
    appId: '1:284300220036:ios:e22b86eaf030d9e4d4d4d1',
    messagingSenderId: '284300220036',
    projectId: 'chat-clone-cbea7',
    storageBucket: 'chat-clone-cbea7.appspot.com',
    iosClientId: '284300220036-016mkerh1bl5bn4deqr04v1gsb4lc323.apps.googleusercontent.com',
    iosBundleId: 'com.example.telChat',
  );
}
